---
- hosts: localhost
  remote_user: kevindurb

  tasks:
    - name: setup pull job
      cron:
        name: 'pull workstation repo'
        minute: '*/30'
        job: '/usr/bin/ansible-pull -o -U https://github.com/kevindurb/workstation.git ./main.yaml'
