---
- hosts: localhost

  vars:
    npm_packages:
      - neovim
      - bash-language-server

  roles:
    - role: stephdewit.nvm
      nvm_version: HEAD
      nvm_node_version: stable

  tasks:
    - include_vars: "{{ ansible_os_family|lower }}.yaml"
    - include_tasks: "./{{ ansible_os_family|lower }}.yaml"

    - name: install npm packages
      npm:
        name: "{{ item }}"
        global: yes
        state: present
      loop: "{{ npm_packages }}"

    - name: setup dotfiles
      git:
        repo: git@github.com:kevindurb/.dotfiles.git
        dest: ~/.dotfiles

    - name: setup dotfiles
      make:
        target: link
        chdir: ~/.dotfiles

    - name: get zsh path
      command: which zsh
      register: zsh_path

    - name: set shell to zsh
      become: yes
      user:
        name: "{{ ansible_user }}"
        shell: "{{ zsh_path.stdout }}"

    - name: Add user to docker group
      become: yes
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes
