---
- hosts: localhost
  remote_user: kevindurb

  vars_files:
    - "./vars/main.yaml"

  tasks:
    - include_vars: "{{ ansible_os_family|lower }}.yaml"
    - include_tasks: "./{{ ansible_os_family|lower }}.yaml"
